version : '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    ports: 
      - "8000:8000"
    env_file:
      - ./backend/.env

  worker_high:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    hostname: high_worker
    command: ["celery", "-A", "src.worker", "worker", "-Q", "high_priority", "--loglevel=info", "--without-gossip", "--without-mingle", "--without-heartbeat"]
    env_file:
      - ./backend/.env

  worker_normal:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    hostname: normal_worker
    command: ["celery", "-A", "src.worker", "worker", "-Q", "normal_priority", "--loglevel=info", "--without-gossip", "--without-mingle", "--without-heartbeat"]
    env_file:
      - ./backend/.env

  worker_low:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    hostname: low_worker
    command: ["celery", "-A", "src.worker", "worker", "-Q", "low_priority", "--loglevel=info", "--without-gossip", "--without-mingle", "--without-heartbeat"]
    env_file:
      - ./backend/.env        

